/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SignOut } from "./SignOut";
import { SignOutCountArgs } from "./SignOutCountArgs";
import { SignOutFindManyArgs } from "./SignOutFindManyArgs";
import { SignOutFindUniqueArgs } from "./SignOutFindUniqueArgs";
import { DeleteSignOutArgs } from "./DeleteSignOutArgs";
import { SignOutService } from "../signOut.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => SignOut)
export class SignOutResolverBase {
  constructor(
    protected readonly service: SignOutService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "SignOut",
    action: "read",
    possession: "any",
  })
  async _signOutsMeta(
    @graphql.Args() args: SignOutCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [SignOut])
  @nestAccessControl.UseRoles({
    resource: "SignOut",
    action: "read",
    possession: "any",
  })
  async signOuts(
    @graphql.Args() args: SignOutFindManyArgs
  ): Promise<SignOut[]> {
    return this.service.signOuts(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => SignOut, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "SignOut",
    action: "read",
    possession: "own",
  })
  async signOut(
    @graphql.Args() args: SignOutFindUniqueArgs
  ): Promise<SignOut | null> {
    const result = await this.service.signOut(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => SignOut)
  @nestAccessControl.UseRoles({
    resource: "SignOut",
    action: "delete",
    possession: "any",
  })
  async deleteSignOut(
    @graphql.Args() args: DeleteSignOutArgs
  ): Promise<SignOut | null> {
    try {
      return await this.service.deleteSignOut(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
