/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AnnouncementsService } from "../announcements.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AnnouncementsCreateInput } from "./AnnouncementsCreateInput";
import { Announcements } from "./Announcements";
import { AnnouncementsFindManyArgs } from "./AnnouncementsFindManyArgs";
import { AnnouncementsWhereUniqueInput } from "./AnnouncementsWhereUniqueInput";
import { AnnouncementsUpdateInput } from "./AnnouncementsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AnnouncementsControllerBase {
  constructor(
    protected readonly service: AnnouncementsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Announcements })
  @nestAccessControl.UseRoles({
    resource: "Announcements",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAnnouncements(
    @common.Body() data: AnnouncementsCreateInput
  ): Promise<Announcements> {
    return await this.service.createAnnouncements({
      data: data,
      select: {
        content: true,
        createdAt: true,
        id: true,
        publishedDate: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Announcements] })
  @ApiNestedQuery(AnnouncementsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Announcements",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async announcementsItems(
    @common.Req() request: Request
  ): Promise<Announcements[]> {
    const args = plainToClass(AnnouncementsFindManyArgs, request.query);
    return this.service.announcementsItems({
      ...args,
      select: {
        content: true,
        createdAt: true,
        id: true,
        publishedDate: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Announcements })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Announcements",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async announcements(
    @common.Param() params: AnnouncementsWhereUniqueInput
  ): Promise<Announcements | null> {
    const result = await this.service.announcements({
      where: params,
      select: {
        content: true,
        createdAt: true,
        id: true,
        publishedDate: true,
        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Announcements })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Announcements",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAnnouncements(
    @common.Param() params: AnnouncementsWhereUniqueInput,
    @common.Body() data: AnnouncementsUpdateInput
  ): Promise<Announcements | null> {
    try {
      return await this.service.updateAnnouncements({
        where: params,
        data: data,
        select: {
          content: true,
          createdAt: true,
          id: true,
          publishedDate: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Announcements })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Announcements",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAnnouncements(
    @common.Param() params: AnnouncementsWhereUniqueInput
  ): Promise<Announcements | null> {
    try {
      return await this.service.deleteAnnouncements({
        where: params,
        select: {
          content: true,
          createdAt: true,
          id: true,
          publishedDate: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
