/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ContingencyPlan } from "./ContingencyPlan";
import { ContingencyPlanCountArgs } from "./ContingencyPlanCountArgs";
import { ContingencyPlanFindManyArgs } from "./ContingencyPlanFindManyArgs";
import { ContingencyPlanFindUniqueArgs } from "./ContingencyPlanFindUniqueArgs";
import { DeleteContingencyPlanArgs } from "./DeleteContingencyPlanArgs";
import { ContingencyPlanService } from "../contingencyPlan.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ContingencyPlan)
export class ContingencyPlanResolverBase {
  constructor(
    protected readonly service: ContingencyPlanService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ContingencyPlan",
    action: "read",
    possession: "any",
  })
  async _contingencyPlansMeta(
    @graphql.Args() args: ContingencyPlanCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ContingencyPlan])
  @nestAccessControl.UseRoles({
    resource: "ContingencyPlan",
    action: "read",
    possession: "any",
  })
  async contingencyPlans(
    @graphql.Args() args: ContingencyPlanFindManyArgs
  ): Promise<ContingencyPlan[]> {
    return this.service.contingencyPlans(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ContingencyPlan, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ContingencyPlan",
    action: "read",
    possession: "own",
  })
  async contingencyPlan(
    @graphql.Args() args: ContingencyPlanFindUniqueArgs
  ): Promise<ContingencyPlan | null> {
    const result = await this.service.contingencyPlan(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ContingencyPlan)
  @nestAccessControl.UseRoles({
    resource: "ContingencyPlan",
    action: "delete",
    possession: "any",
  })
  async deleteContingencyPlan(
    @graphql.Args() args: DeleteContingencyPlanArgs
  ): Promise<ContingencyPlan | null> {
    try {
      return await this.service.deleteContingencyPlan(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
