/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TaskAssignment } from "./TaskAssignment";
import { TaskAssignmentCountArgs } from "./TaskAssignmentCountArgs";
import { TaskAssignmentFindManyArgs } from "./TaskAssignmentFindManyArgs";
import { TaskAssignmentFindUniqueArgs } from "./TaskAssignmentFindUniqueArgs";
import { DeleteTaskAssignmentArgs } from "./DeleteTaskAssignmentArgs";
import { TaskAssignmentService } from "../taskAssignment.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => TaskAssignment)
export class TaskAssignmentResolverBase {
  constructor(
    protected readonly service: TaskAssignmentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "TaskAssignment",
    action: "read",
    possession: "any",
  })
  async _taskAssignmentsMeta(
    @graphql.Args() args: TaskAssignmentCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [TaskAssignment])
  @nestAccessControl.UseRoles({
    resource: "TaskAssignment",
    action: "read",
    possession: "any",
  })
  async taskAssignments(
    @graphql.Args() args: TaskAssignmentFindManyArgs
  ): Promise<TaskAssignment[]> {
    return this.service.taskAssignments(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => TaskAssignment, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "TaskAssignment",
    action: "read",
    possession: "own",
  })
  async taskAssignment(
    @graphql.Args() args: TaskAssignmentFindUniqueArgs
  ): Promise<TaskAssignment | null> {
    const result = await this.service.taskAssignment(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => TaskAssignment)
  @nestAccessControl.UseRoles({
    resource: "TaskAssignment",
    action: "delete",
    possession: "any",
  })
  async deleteTaskAssignment(
    @graphql.Args() args: DeleteTaskAssignmentArgs
  ): Promise<TaskAssignment | null> {
    try {
      return await this.service.deleteTaskAssignment(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
