/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { GoalsAnalytics } from "./GoalsAnalytics";
import { GoalsAnalyticsCountArgs } from "./GoalsAnalyticsCountArgs";
import { GoalsAnalyticsFindManyArgs } from "./GoalsAnalyticsFindManyArgs";
import { GoalsAnalyticsFindUniqueArgs } from "./GoalsAnalyticsFindUniqueArgs";
import { DeleteGoalsAnalyticsArgs } from "./DeleteGoalsAnalyticsArgs";
import { GoalsAnalyticsService } from "../goalsAnalytics.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => GoalsAnalytics)
export class GoalsAnalyticsResolverBase {
  constructor(
    protected readonly service: GoalsAnalyticsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "GoalsAnalytics",
    action: "read",
    possession: "any",
  })
  async _goalsAnalyticsItemsMeta(
    @graphql.Args() args: GoalsAnalyticsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [GoalsAnalytics])
  @nestAccessControl.UseRoles({
    resource: "GoalsAnalytics",
    action: "read",
    possession: "any",
  })
  async goalsAnalyticsItems(
    @graphql.Args() args: GoalsAnalyticsFindManyArgs
  ): Promise<GoalsAnalytics[]> {
    return this.service.goalsAnalyticsItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => GoalsAnalytics, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "GoalsAnalytics",
    action: "read",
    possession: "own",
  })
  async goalsAnalytics(
    @graphql.Args() args: GoalsAnalyticsFindUniqueArgs
  ): Promise<GoalsAnalytics | null> {
    const result = await this.service.goalsAnalytics(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => GoalsAnalytics)
  @nestAccessControl.UseRoles({
    resource: "GoalsAnalytics",
    action: "delete",
    possession: "any",
  })
  async deleteGoalsAnalytics(
    @graphql.Args() args: DeleteGoalsAnalyticsArgs
  ): Promise<GoalsAnalytics | null> {
    try {
      return await this.service.deleteGoalsAnalytics(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
