/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { GoalsAnalyticsService } from "../goalsAnalytics.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { GoalsAnalyticsCreateInput } from "./GoalsAnalyticsCreateInput";
import { GoalsAnalytics } from "./GoalsAnalytics";
import { GoalsAnalyticsFindManyArgs } from "./GoalsAnalyticsFindManyArgs";
import { GoalsAnalyticsWhereUniqueInput } from "./GoalsAnalyticsWhereUniqueInput";
import { GoalsAnalyticsUpdateInput } from "./GoalsAnalyticsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class GoalsAnalyticsControllerBase {
  constructor(
    protected readonly service: GoalsAnalyticsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: GoalsAnalytics })
  @nestAccessControl.UseRoles({
    resource: "GoalsAnalytics",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createGoalsAnalytics(
    @common.Body() data: GoalsAnalyticsCreateInput
  ): Promise<GoalsAnalytics> {
    return await this.service.createGoalsAnalytics({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [GoalsAnalytics] })
  @ApiNestedQuery(GoalsAnalyticsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "GoalsAnalytics",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async goalsAnalyticsItems(
    @common.Req() request: Request
  ): Promise<GoalsAnalytics[]> {
    const args = plainToClass(GoalsAnalyticsFindManyArgs, request.query);
    return this.service.goalsAnalyticsItems({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: GoalsAnalytics })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "GoalsAnalytics",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async goalsAnalytics(
    @common.Param() params: GoalsAnalyticsWhereUniqueInput
  ): Promise<GoalsAnalytics | null> {
    const result = await this.service.goalsAnalytics({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: GoalsAnalytics })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "GoalsAnalytics",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateGoalsAnalytics(
    @common.Param() params: GoalsAnalyticsWhereUniqueInput,
    @common.Body() data: GoalsAnalyticsUpdateInput
  ): Promise<GoalsAnalytics | null> {
    try {
      return await this.service.updateGoalsAnalytics({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: GoalsAnalytics })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "GoalsAnalytics",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteGoalsAnalytics(
    @common.Param() params: GoalsAnalyticsWhereUniqueInput
  ): Promise<GoalsAnalytics | null> {
    try {
      return await this.service.deleteGoalsAnalytics({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
