/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { OperationalPerformance } from "./OperationalPerformance";
import { OperationalPerformanceCountArgs } from "./OperationalPerformanceCountArgs";
import { OperationalPerformanceFindManyArgs } from "./OperationalPerformanceFindManyArgs";
import { OperationalPerformanceFindUniqueArgs } from "./OperationalPerformanceFindUniqueArgs";
import { DeleteOperationalPerformanceArgs } from "./DeleteOperationalPerformanceArgs";
import { OperationalPerformanceService } from "../operationalPerformance.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => OperationalPerformance)
export class OperationalPerformanceResolverBase {
  constructor(
    protected readonly service: OperationalPerformanceService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "OperationalPerformance",
    action: "read",
    possession: "any",
  })
  async _operationalPerformancesMeta(
    @graphql.Args() args: OperationalPerformanceCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [OperationalPerformance])
  @nestAccessControl.UseRoles({
    resource: "OperationalPerformance",
    action: "read",
    possession: "any",
  })
  async operationalPerformances(
    @graphql.Args() args: OperationalPerformanceFindManyArgs
  ): Promise<OperationalPerformance[]> {
    return this.service.operationalPerformances(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => OperationalPerformance, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "OperationalPerformance",
    action: "read",
    possession: "own",
  })
  async operationalPerformance(
    @graphql.Args() args: OperationalPerformanceFindUniqueArgs
  ): Promise<OperationalPerformance | null> {
    const result = await this.service.operationalPerformance(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => OperationalPerformance)
  @nestAccessControl.UseRoles({
    resource: "OperationalPerformance",
    action: "delete",
    possession: "any",
  })
  async deleteOperationalPerformance(
    @graphql.Args() args: DeleteOperationalPerformanceArgs
  ): Promise<OperationalPerformance | null> {
    try {
      return await this.service.deleteOperationalPerformance(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
