/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { OperationalPerformanceService } from "../operationalPerformance.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { OperationalPerformanceCreateInput } from "./OperationalPerformanceCreateInput";
import { OperationalPerformance } from "./OperationalPerformance";
import { OperationalPerformanceFindManyArgs } from "./OperationalPerformanceFindManyArgs";
import { OperationalPerformanceWhereUniqueInput } from "./OperationalPerformanceWhereUniqueInput";
import { OperationalPerformanceUpdateInput } from "./OperationalPerformanceUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class OperationalPerformanceControllerBase {
  constructor(
    protected readonly service: OperationalPerformanceService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: OperationalPerformance })
  @nestAccessControl.UseRoles({
    resource: "OperationalPerformance",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createOperationalPerformance(
    @common.Body() data: OperationalPerformanceCreateInput
  ): Promise<OperationalPerformance> {
    return await this.service.createOperationalPerformance({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [OperationalPerformance] })
  @ApiNestedQuery(OperationalPerformanceFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "OperationalPerformance",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async operationalPerformances(
    @common.Req() request: Request
  ): Promise<OperationalPerformance[]> {
    const args = plainToClass(
      OperationalPerformanceFindManyArgs,
      request.query
    );
    return this.service.operationalPerformances({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: OperationalPerformance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "OperationalPerformance",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async operationalPerformance(
    @common.Param() params: OperationalPerformanceWhereUniqueInput
  ): Promise<OperationalPerformance | null> {
    const result = await this.service.operationalPerformance({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: OperationalPerformance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "OperationalPerformance",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateOperationalPerformance(
    @common.Param() params: OperationalPerformanceWhereUniqueInput,
    @common.Body() data: OperationalPerformanceUpdateInput
  ): Promise<OperationalPerformance | null> {
    try {
      return await this.service.updateOperationalPerformance({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: OperationalPerformance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "OperationalPerformance",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteOperationalPerformance(
    @common.Param() params: OperationalPerformanceWhereUniqueInput
  ): Promise<OperationalPerformance | null> {
    try {
      return await this.service.deleteOperationalPerformance({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
