/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ExecutiveSummary } from "./ExecutiveSummary";
import { ExecutiveSummaryCountArgs } from "./ExecutiveSummaryCountArgs";
import { ExecutiveSummaryFindManyArgs } from "./ExecutiveSummaryFindManyArgs";
import { ExecutiveSummaryFindUniqueArgs } from "./ExecutiveSummaryFindUniqueArgs";
import { DeleteExecutiveSummaryArgs } from "./DeleteExecutiveSummaryArgs";
import { ExecutiveSummaryService } from "../executiveSummary.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ExecutiveSummary)
export class ExecutiveSummaryResolverBase {
  constructor(
    protected readonly service: ExecutiveSummaryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ExecutiveSummary",
    action: "read",
    possession: "any",
  })
  async _executiveSummariesMeta(
    @graphql.Args() args: ExecutiveSummaryCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ExecutiveSummary])
  @nestAccessControl.UseRoles({
    resource: "ExecutiveSummary",
    action: "read",
    possession: "any",
  })
  async executiveSummaries(
    @graphql.Args() args: ExecutiveSummaryFindManyArgs
  ): Promise<ExecutiveSummary[]> {
    return this.service.executiveSummaries(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ExecutiveSummary, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ExecutiveSummary",
    action: "read",
    possession: "own",
  })
  async executiveSummary(
    @graphql.Args() args: ExecutiveSummaryFindUniqueArgs
  ): Promise<ExecutiveSummary | null> {
    const result = await this.service.executiveSummary(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ExecutiveSummary)
  @nestAccessControl.UseRoles({
    resource: "ExecutiveSummary",
    action: "delete",
    possession: "any",
  })
  async deleteExecutiveSummary(
    @graphql.Args() args: DeleteExecutiveSummaryArgs
  ): Promise<ExecutiveSummary | null> {
    try {
      return await this.service.deleteExecutiveSummary(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
