/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { GoalAssignmentsService } from "../goalAssignments.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { GoalAssignmentsCreateInput } from "./GoalAssignmentsCreateInput";
import { GoalAssignments } from "./GoalAssignments";
import { GoalAssignmentsFindManyArgs } from "./GoalAssignmentsFindManyArgs";
import { GoalAssignmentsWhereUniqueInput } from "./GoalAssignmentsWhereUniqueInput";
import { GoalAssignmentsUpdateInput } from "./GoalAssignmentsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class GoalAssignmentsControllerBase {
  constructor(
    protected readonly service: GoalAssignmentsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: GoalAssignments })
  @nestAccessControl.UseRoles({
    resource: "GoalAssignments",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createGoalAssignments(
    @common.Body() data: GoalAssignmentsCreateInput
  ): Promise<GoalAssignments> {
    return await this.service.createGoalAssignments({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [GoalAssignments] })
  @ApiNestedQuery(GoalAssignmentsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "GoalAssignments",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async goalAssignmentsItems(
    @common.Req() request: Request
  ): Promise<GoalAssignments[]> {
    const args = plainToClass(GoalAssignmentsFindManyArgs, request.query);
    return this.service.goalAssignmentsItems({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: GoalAssignments })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "GoalAssignments",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async goalAssignments(
    @common.Param() params: GoalAssignmentsWhereUniqueInput
  ): Promise<GoalAssignments | null> {
    const result = await this.service.goalAssignments({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: GoalAssignments })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "GoalAssignments",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateGoalAssignments(
    @common.Param() params: GoalAssignmentsWhereUniqueInput,
    @common.Body() data: GoalAssignmentsUpdateInput
  ): Promise<GoalAssignments | null> {
    try {
      return await this.service.updateGoalAssignments({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: GoalAssignments })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "GoalAssignments",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteGoalAssignments(
    @common.Param() params: GoalAssignmentsWhereUniqueInput
  ): Promise<GoalAssignments | null> {
    try {
      return await this.service.deleteGoalAssignments({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
