/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Tickets as PrismaTickets } from "@prisma/client";

export class TicketsServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.TicketsCountArgs, "select">): Promise<number> {
    return this.prisma.tickets.count(args);
  }

  async ticketsItems(
    args: Prisma.TicketsFindManyArgs
  ): Promise<PrismaTickets[]> {
    return this.prisma.tickets.findMany(args);
  }
  async tickets(
    args: Prisma.TicketsFindUniqueArgs
  ): Promise<PrismaTickets | null> {
    return this.prisma.tickets.findUnique(args);
  }
  async createTickets(args: Prisma.TicketsCreateArgs): Promise<PrismaTickets> {
    return this.prisma.tickets.create(args);
  }
  async updateTickets(args: Prisma.TicketsUpdateArgs): Promise<PrismaTickets> {
    return this.prisma.tickets.update(args);
  }
  async deleteTickets(args: Prisma.TicketsDeleteArgs): Promise<PrismaTickets> {
    return this.prisma.tickets.delete(args);
  }
}
