/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Tickets } from "./Tickets";
import { TicketsCountArgs } from "./TicketsCountArgs";
import { TicketsFindManyArgs } from "./TicketsFindManyArgs";
import { TicketsFindUniqueArgs } from "./TicketsFindUniqueArgs";
import { DeleteTicketsArgs } from "./DeleteTicketsArgs";
import { TicketsService } from "../tickets.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Tickets)
export class TicketsResolverBase {
  constructor(
    protected readonly service: TicketsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Tickets",
    action: "read",
    possession: "any",
  })
  async _ticketsItemsMeta(
    @graphql.Args() args: TicketsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Tickets])
  @nestAccessControl.UseRoles({
    resource: "Tickets",
    action: "read",
    possession: "any",
  })
  async ticketsItems(
    @graphql.Args() args: TicketsFindManyArgs
  ): Promise<Tickets[]> {
    return this.service.ticketsItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Tickets, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Tickets",
    action: "read",
    possession: "own",
  })
  async tickets(
    @graphql.Args() args: TicketsFindUniqueArgs
  ): Promise<Tickets | null> {
    const result = await this.service.tickets(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Tickets)
  @nestAccessControl.UseRoles({
    resource: "Tickets",
    action: "delete",
    possession: "any",
  })
  async deleteTickets(
    @graphql.Args() args: DeleteTicketsArgs
  ): Promise<Tickets | null> {
    try {
      return await this.service.deleteTickets(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
