/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Collaboration } from "./Collaboration";
import { CollaborationCountArgs } from "./CollaborationCountArgs";
import { CollaborationFindManyArgs } from "./CollaborationFindManyArgs";
import { CollaborationFindUniqueArgs } from "./CollaborationFindUniqueArgs";
import { DeleteCollaborationArgs } from "./DeleteCollaborationArgs";
import { CollaborationService } from "../collaboration.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Collaboration)
export class CollaborationResolverBase {
  constructor(
    protected readonly service: CollaborationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Collaboration",
    action: "read",
    possession: "any",
  })
  async _collaborationsMeta(
    @graphql.Args() args: CollaborationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Collaboration])
  @nestAccessControl.UseRoles({
    resource: "Collaboration",
    action: "read",
    possession: "any",
  })
  async collaborations(
    @graphql.Args() args: CollaborationFindManyArgs
  ): Promise<Collaboration[]> {
    return this.service.collaborations(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Collaboration, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Collaboration",
    action: "read",
    possession: "own",
  })
  async collaboration(
    @graphql.Args() args: CollaborationFindUniqueArgs
  ): Promise<Collaboration | null> {
    const result = await this.service.collaboration(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Collaboration)
  @nestAccessControl.UseRoles({
    resource: "Collaboration",
    action: "delete",
    possession: "any",
  })
  async deleteCollaboration(
    @graphql.Args() args: DeleteCollaborationArgs
  ): Promise<Collaboration | null> {
    try {
      return await this.service.deleteCollaboration(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
