/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { QualityInspection } from "./QualityInspection";
import { QualityInspectionCountArgs } from "./QualityInspectionCountArgs";
import { QualityInspectionFindManyArgs } from "./QualityInspectionFindManyArgs";
import { QualityInspectionFindUniqueArgs } from "./QualityInspectionFindUniqueArgs";
import { DeleteQualityInspectionArgs } from "./DeleteQualityInspectionArgs";
import { QualityInspectionService } from "../qualityInspection.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => QualityInspection)
export class QualityInspectionResolverBase {
  constructor(
    protected readonly service: QualityInspectionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "QualityInspection",
    action: "read",
    possession: "any",
  })
  async _qualityInspectionsMeta(
    @graphql.Args() args: QualityInspectionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [QualityInspection])
  @nestAccessControl.UseRoles({
    resource: "QualityInspection",
    action: "read",
    possession: "any",
  })
  async qualityInspections(
    @graphql.Args() args: QualityInspectionFindManyArgs
  ): Promise<QualityInspection[]> {
    return this.service.qualityInspections(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => QualityInspection, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "QualityInspection",
    action: "read",
    possession: "own",
  })
  async qualityInspection(
    @graphql.Args() args: QualityInspectionFindUniqueArgs
  ): Promise<QualityInspection | null> {
    const result = await this.service.qualityInspection(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => QualityInspection)
  @nestAccessControl.UseRoles({
    resource: "QualityInspection",
    action: "delete",
    possession: "any",
  })
  async deleteQualityInspection(
    @graphql.Args() args: DeleteQualityInspectionArgs
  ): Promise<QualityInspection | null> {
    try {
      return await this.service.deleteQualityInspection(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
