/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ComplianceAndQuality } from "./ComplianceAndQuality";
import { ComplianceAndQualityCountArgs } from "./ComplianceAndQualityCountArgs";
import { ComplianceAndQualityFindManyArgs } from "./ComplianceAndQualityFindManyArgs";
import { ComplianceAndQualityFindUniqueArgs } from "./ComplianceAndQualityFindUniqueArgs";
import { DeleteComplianceAndQualityArgs } from "./DeleteComplianceAndQualityArgs";
import { ComplianceAndQualityService } from "../complianceAndQuality.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ComplianceAndQuality)
export class ComplianceAndQualityResolverBase {
  constructor(
    protected readonly service: ComplianceAndQualityService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ComplianceAndQuality",
    action: "read",
    possession: "any",
  })
  async _complianceAndQualitiesMeta(
    @graphql.Args() args: ComplianceAndQualityCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ComplianceAndQuality])
  @nestAccessControl.UseRoles({
    resource: "ComplianceAndQuality",
    action: "read",
    possession: "any",
  })
  async complianceAndQualities(
    @graphql.Args() args: ComplianceAndQualityFindManyArgs
  ): Promise<ComplianceAndQuality[]> {
    return this.service.complianceAndQualities(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ComplianceAndQuality, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ComplianceAndQuality",
    action: "read",
    possession: "own",
  })
  async complianceAndQuality(
    @graphql.Args() args: ComplianceAndQualityFindUniqueArgs
  ): Promise<ComplianceAndQuality | null> {
    const result = await this.service.complianceAndQuality(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ComplianceAndQuality)
  @nestAccessControl.UseRoles({
    resource: "ComplianceAndQuality",
    action: "delete",
    possession: "any",
  })
  async deleteComplianceAndQuality(
    @graphql.Args() args: DeleteComplianceAndQualityArgs
  ): Promise<ComplianceAndQuality | null> {
    try {
      return await this.service.deleteComplianceAndQuality(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
