/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { FeedbackLoop } from "./FeedbackLoop";
import { FeedbackLoopCountArgs } from "./FeedbackLoopCountArgs";
import { FeedbackLoopFindManyArgs } from "./FeedbackLoopFindManyArgs";
import { FeedbackLoopFindUniqueArgs } from "./FeedbackLoopFindUniqueArgs";
import { DeleteFeedbackLoopArgs } from "./DeleteFeedbackLoopArgs";
import { FeedbackLoopService } from "../feedbackLoop.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => FeedbackLoop)
export class FeedbackLoopResolverBase {
  constructor(
    protected readonly service: FeedbackLoopService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "FeedbackLoop",
    action: "read",
    possession: "any",
  })
  async _feedbackLoopsMeta(
    @graphql.Args() args: FeedbackLoopCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [FeedbackLoop])
  @nestAccessControl.UseRoles({
    resource: "FeedbackLoop",
    action: "read",
    possession: "any",
  })
  async feedbackLoops(
    @graphql.Args() args: FeedbackLoopFindManyArgs
  ): Promise<FeedbackLoop[]> {
    return this.service.feedbackLoops(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => FeedbackLoop, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "FeedbackLoop",
    action: "read",
    possession: "own",
  })
  async feedbackLoop(
    @graphql.Args() args: FeedbackLoopFindUniqueArgs
  ): Promise<FeedbackLoop | null> {
    const result = await this.service.feedbackLoop(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => FeedbackLoop)
  @nestAccessControl.UseRoles({
    resource: "FeedbackLoop",
    action: "delete",
    possession: "any",
  })
  async deleteFeedbackLoop(
    @graphql.Args() args: DeleteFeedbackLoopArgs
  ): Promise<FeedbackLoop | null> {
    try {
      return await this.service.deleteFeedbackLoop(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
