/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { FeedbackLoopService } from "../feedbackLoop.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { FeedbackLoopCreateInput } from "./FeedbackLoopCreateInput";
import { FeedbackLoop } from "./FeedbackLoop";
import { FeedbackLoopFindManyArgs } from "./FeedbackLoopFindManyArgs";
import { FeedbackLoopWhereUniqueInput } from "./FeedbackLoopWhereUniqueInput";
import { FeedbackLoopUpdateInput } from "./FeedbackLoopUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class FeedbackLoopControllerBase {
  constructor(
    protected readonly service: FeedbackLoopService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: FeedbackLoop })
  @nestAccessControl.UseRoles({
    resource: "FeedbackLoop",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createFeedbackLoop(
    @common.Body() data: FeedbackLoopCreateInput
  ): Promise<FeedbackLoop> {
    return await this.service.createFeedbackLoop({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [FeedbackLoop] })
  @ApiNestedQuery(FeedbackLoopFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "FeedbackLoop",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async feedbackLoops(@common.Req() request: Request): Promise<FeedbackLoop[]> {
    const args = plainToClass(FeedbackLoopFindManyArgs, request.query);
    return this.service.feedbackLoops({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: FeedbackLoop })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FeedbackLoop",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async feedbackLoop(
    @common.Param() params: FeedbackLoopWhereUniqueInput
  ): Promise<FeedbackLoop | null> {
    const result = await this.service.feedbackLoop({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: FeedbackLoop })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FeedbackLoop",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateFeedbackLoop(
    @common.Param() params: FeedbackLoopWhereUniqueInput,
    @common.Body() data: FeedbackLoopUpdateInput
  ): Promise<FeedbackLoop | null> {
    try {
      return await this.service.updateFeedbackLoop({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: FeedbackLoop })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FeedbackLoop",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteFeedbackLoop(
    @common.Param() params: FeedbackLoopWhereUniqueInput
  ): Promise<FeedbackLoop | null> {
    try {
      return await this.service.deleteFeedbackLoop({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
