/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { WorkInstruction } from "./WorkInstruction";
import { WorkInstructionCountArgs } from "./WorkInstructionCountArgs";
import { WorkInstructionFindManyArgs } from "./WorkInstructionFindManyArgs";
import { WorkInstructionFindUniqueArgs } from "./WorkInstructionFindUniqueArgs";
import { DeleteWorkInstructionArgs } from "./DeleteWorkInstructionArgs";
import { WorkInstructionService } from "../workInstruction.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => WorkInstruction)
export class WorkInstructionResolverBase {
  constructor(
    protected readonly service: WorkInstructionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "WorkInstruction",
    action: "read",
    possession: "any",
  })
  async _workInstructionsMeta(
    @graphql.Args() args: WorkInstructionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [WorkInstruction])
  @nestAccessControl.UseRoles({
    resource: "WorkInstruction",
    action: "read",
    possession: "any",
  })
  async workInstructions(
    @graphql.Args() args: WorkInstructionFindManyArgs
  ): Promise<WorkInstruction[]> {
    return this.service.workInstructions(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => WorkInstruction, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "WorkInstruction",
    action: "read",
    possession: "own",
  })
  async workInstruction(
    @graphql.Args() args: WorkInstructionFindUniqueArgs
  ): Promise<WorkInstruction | null> {
    const result = await this.service.workInstruction(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => WorkInstruction)
  @nestAccessControl.UseRoles({
    resource: "WorkInstruction",
    action: "delete",
    possession: "any",
  })
  async deleteWorkInstruction(
    @graphql.Args() args: DeleteWorkInstructionArgs
  ): Promise<WorkInstruction | null> {
    try {
      return await this.service.deleteWorkInstruction(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
