/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PeriodicGoalsService } from "../periodicGoals.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PeriodicGoalsCreateInput } from "./PeriodicGoalsCreateInput";
import { PeriodicGoals } from "./PeriodicGoals";
import { PeriodicGoalsFindManyArgs } from "./PeriodicGoalsFindManyArgs";
import { PeriodicGoalsWhereUniqueInput } from "./PeriodicGoalsWhereUniqueInput";
import { PeriodicGoalsUpdateInput } from "./PeriodicGoalsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PeriodicGoalsControllerBase {
  constructor(
    protected readonly service: PeriodicGoalsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PeriodicGoals })
  @nestAccessControl.UseRoles({
    resource: "PeriodicGoals",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPeriodicGoals(
    @common.Body() data: PeriodicGoalsCreateInput
  ): Promise<PeriodicGoals> {
    return await this.service.createPeriodicGoals({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PeriodicGoals] })
  @ApiNestedQuery(PeriodicGoalsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PeriodicGoals",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async periodicGoalsItems(
    @common.Req() request: Request
  ): Promise<PeriodicGoals[]> {
    const args = plainToClass(PeriodicGoalsFindManyArgs, request.query);
    return this.service.periodicGoalsItems({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PeriodicGoals })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PeriodicGoals",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async periodicGoals(
    @common.Param() params: PeriodicGoalsWhereUniqueInput
  ): Promise<PeriodicGoals | null> {
    const result = await this.service.periodicGoals({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PeriodicGoals })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PeriodicGoals",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePeriodicGoals(
    @common.Param() params: PeriodicGoalsWhereUniqueInput,
    @common.Body() data: PeriodicGoalsUpdateInput
  ): Promise<PeriodicGoals | null> {
    try {
      return await this.service.updatePeriodicGoals({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PeriodicGoals })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PeriodicGoals",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePeriodicGoals(
    @common.Param() params: PeriodicGoalsWhereUniqueInput
  ): Promise<PeriodicGoals | null> {
    try {
      return await this.service.deletePeriodicGoals({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
