/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PeriodicGoals } from "./PeriodicGoals";
import { PeriodicGoalsCountArgs } from "./PeriodicGoalsCountArgs";
import { PeriodicGoalsFindManyArgs } from "./PeriodicGoalsFindManyArgs";
import { PeriodicGoalsFindUniqueArgs } from "./PeriodicGoalsFindUniqueArgs";
import { DeletePeriodicGoalsArgs } from "./DeletePeriodicGoalsArgs";
import { PeriodicGoalsService } from "../periodicGoals.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => PeriodicGoals)
export class PeriodicGoalsResolverBase {
  constructor(
    protected readonly service: PeriodicGoalsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "PeriodicGoals",
    action: "read",
    possession: "any",
  })
  async _periodicGoalsItemsMeta(
    @graphql.Args() args: PeriodicGoalsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [PeriodicGoals])
  @nestAccessControl.UseRoles({
    resource: "PeriodicGoals",
    action: "read",
    possession: "any",
  })
  async periodicGoalsItems(
    @graphql.Args() args: PeriodicGoalsFindManyArgs
  ): Promise<PeriodicGoals[]> {
    return this.service.periodicGoalsItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => PeriodicGoals, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "PeriodicGoals",
    action: "read",
    possession: "own",
  })
  async periodicGoals(
    @graphql.Args() args: PeriodicGoalsFindUniqueArgs
  ): Promise<PeriodicGoals | null> {
    const result = await this.service.periodicGoals(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => PeriodicGoals)
  @nestAccessControl.UseRoles({
    resource: "PeriodicGoals",
    action: "delete",
    possession: "any",
  })
  async deletePeriodicGoals(
    @graphql.Args() args: DeletePeriodicGoalsArgs
  ): Promise<PeriodicGoals | null> {
    try {
      return await this.service.deletePeriodicGoals(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
